### ISSUE TITLE
Health Questions Section 

### ISSUE THREAD

**Issue by timtimmytime** [timtimmytime/ywam-apply-webapp-firebase#11]
on application form 

What text do we need to include ?

> We will do our best to accommodate for your needs but can not guarantee that we can facilitate for every special need or request.

We could make location notice for Health Insurance text as it will be specific to locations. 
> Medical Insurance 
> You will be responsible to pay for your own health insurance. All full-time staff are required by the German government to have German health insurance. If you are German, you may use your current insurance. If you are a non-German, then you will need to purchase German insurance to obtain your visa, and we will help you with that process.

**Comment by AshThor** [comment]
Hey mate. I like what you have done with the check boxes. I think its great to have as many 'common' options readily available to check. It would be good to have a line appear to fill out if they click 'on medication'. Sometimes people don't mention that they are on some serious stuff. Like anti-depressants or phsyc meds. Maybe filling in the line could be mandatory if you click that you are on meds?

**Comment by timtimmytime** [comment]
So now if the "on medication" check box is checked then another (required) input will appear asking for what medications. Same thing for if they have an "other" allergy. I have removed any text about needing insurance since those details should probably be communicated in the acceptance packet for the school or staff.   
![screen shot 2017-01-23 at 12 06 30 pm](https://cloud.githubusercontent.com/assets/1177839/22214088/6be753b2-e164-11e6-9664-d8595cf5ed22.png)
