### ISSUE TITLE
Check list leading up to arrival

### ISSUE THREAD

**Issue by timtimmytime** [timtimmytime/ywam-apply-webapp-firebase#15]
For accepted students / staff It could be helpful to have a recommended list of things that should be done before coming shown on their dashboard. 

Example: 
- [ ]  vaccinations
- [ ]  invitation letter 
- [ ]  sent flight information to ywam 
- [ ]  additional information form for AFTER they have been accepted

**Comment by svenstuh** [comment]
- passport valid for 6 months after graduation
-

**Comment by timtimmytime** [comment]
moved to ywam-staff-webapp-firebase/issues/90
