### ISSUE TITLE
Reference request form

### ISSUE THREAD

**Issue by timtimmytime** [timtimmytime/ywam-apply-webapp-firebase#2]
Form for applicants to fill out who they want their reference to be with and the system would send email with link back to the reference form.

**Comment by timtimmytime** [comment]
Should we keep the current text?:

> You are nearly finished completing your application! The last step is to select two individuals as references for your application.  
>  These can be anyone! Preferably an individual who can answer a few simple questions to supplement your application.

**Comment by svenstuh** [comment]
I think we could leave the first paragraph. Then something like
"As reference, please choose someone who you trust and who knows you. This could be a pastor, youth leader, mentor, friend, relative,..."

**Comment by kweikle** [comment]
I like the changes for the second paragraph, but for the first can we say "Your application is nearly complete!" ? I'm not a fan of the grammar in the original line.

**Comment by svenstuh** [comment]
"Your application is almost ready to be submitted. As one last step, please select two references to complete the application process. 
A reference should be someone who you trust and who knows you. This could be a pastor, youth leader, mentor, friend, relative,...

**Comment by joernbu** [comment]
Hi guys, 
good points so far. The point of the references is to get a better and genuine idea about who it is that is applying. I believe we get the best idea if get a least two different sources of references. 
1. Pastor/Leader/Parent
2.Friend/Relative

**Comment by AshThor** [comment]
Like what joern added.
Having two differing points of reference would be helpful. Although having a relative reference often turns into a parent. What is often biased and then not helpful. So maybe cutting out relative suggestion.

Could add teacher to Sven's list?

Getting grammar right is good too. Keeping it pro.

**Comment by timtimmytime** [comment]
Bringing together most of your suggestions, here is what I have so far: 
![screen shot 2016-12-01 at 12 54 33 pm](https://cloud.githubusercontent.com/assets/1177839/20793074/8627f970-b7c5-11e6-9d9b-1aa802e74f4d.png)

**Comment by timtimmytime** [comment]
waiting on issue #13

**Comment by timtimmytime** [comment]
This part is done.

**Comment by timtimmytime** [comment]
![screen shot 2017-03-17 at 10 52 30 am](https://cloud.githubusercontent.com/assets/1177839/24048660/f241e002-0aff-11e7-891d-ead7cad9ccce.png)

**Comment by joernbu** [comment]
I would write the first sentence like this, its more simple and without the typos:
"Deine Bewerbung ist fast komplett! Bitte wähle zwei Referenzpersonen aus die dich kennen."  

What do you think about adding a field with a telephone number from References? I think for some people it would be great to to just jump on the phone and ask some more questions.

**Comment by timtimmytime** [comment]
Thanks @joernbu translation has been updated. We do ask the reference for their own phone number in the reference form...
