### ISSUE TITLE
ask if applicant has any Children? And info section 

### ISSUE THREAD

**Issue by timtimmytime** [timtimmytime/ywam-apply-webapp-firebase#31]
@joernbu what would be some good questions to ask in this section?

**Comment by joernbu** [comment]
Hm not sure what kind of info would be interesting to know. For sure the age and gender of the children, depending on what that answer then is it could open up allot more Questions, but that could also be a email conversation afterwards. 

Maybe also, Will you bring your children with you? (More for older people).

**Comment by timtimmytime** [comment]
moved issue to https://github.com/timtimmytime/ywam-staff-webapp-firebase/issues/77
Closing here
